sudo: false
language: generic go c

compiler:
  - gcc

before_install:
  - sudo apt-get install -y libffi-dev
addons:
  apt:
    update: true

go:
  - 1.12.7
  - tip

os:
  - linux
  - osx

matrix:
  allow_failures:
    - go: tip
  fast_finish: true

script:
  - make test