sudo: false
language: go

compiler:
  - gcc

install:
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/mattn/goveralls

before_install:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get install -y libffi-dev; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew update; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew install pkg-config libffi; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then export PKG_CONFIG_PATH="${PKG_CONFIG_PATH}:/usr/local/opt/libffi/lib/pkgconfig"; fi
addons:
  apt:
    update: true

go:
  - 1.12.7
  - tip

env:
  - GO111MODULE=on

os:
  - linux
  - osx

matrix:
  allow_failures:
    - go: tip
  fast_finish: true

script:
  - make test
  - $HOME/gopath/bin/goveralls -coverprofile=coverage.out -service=travis-ci -repotoken $COVERALLS_TOKEN
